### ISSUE TITLE
Inline array description

### ISSUE THREAD

**Issue by FArseny** [artsmolin/pythogen#20]
1) Learn to generate model from inline array item description. Example:
```
rewards:
  type: array
  items:
    type: object
    required: [pricePlanCode, quantity]
    properties:
      pricePlanCode:
        type: string
      quantity:
        type: number
```
In early days it was converted into:
```
class RewardsListItem(BaseModel):
    """
    None
    """

    # required ---
    pricePlanCode: str
    quantity: float

    # optional ---


class RedemptionsRequest(BaseModel):
    """
    None
    """

    # required ---
    rewards: List[RewardsListItem]

    # optional ---
```
Now it's like:
```
class RedemptionsRequest(BaseModel):
    """
    None
    """

    # required ---
    rewards: List[Dict]

    # optional ---
```
2) Learn to generate model from inline object description. Example:
```
UserProfile:
  type: object
  properties:
    id:
      type: integer
    accountId:
      type: integer
    login:
      type: string
    address:
      type: object
      properties:
        mobile:
          type: string
        email:
          type: string
...
```
In early days it was converted into:
```class AddressObj(BaseModel):
    """
    None
    """

    # required ---

    # optional ---
    mobile: Optional[str] = None
    email: Optional[str] = None


class CreateUserProfileRequest(BaseModel):
    """
    None
    """

    # required ---

    # optional ---
    id: int
    accountId: int
    attributes: List[ProfileAttributesItem]
    login: Optional[str] = None
    address: Optional[AddressObj] = None
```
Now `CreateUserProfileRequest` the same, but `AddressObj` class doesn't generated at all
